name: Compliance yeah

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - unassigned

jobs:
  check-for-linked-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: check-for-keywords
      id: check-for-keywords
      uses: actions/github-script@v7
      with:
        script: |
          console.log(context.repo.owner);
          
          // Retrieve current PR
          const currentPR = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1,
            page: 1,
          });

